apiVersion: v1
kind: Service
metadata:
  name: svc-plone-varnish
  labels:
    plone-service: gateway-web
spec:
  type: NodePort
  selector:
    app: zabbix-web
  ports:
  - port: 80
    nodePort: 30000
    name: http
  - port: 8443
    nodePort: 30443
    name: https